In [4]:
# numpy practice 
import numpy as np 
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a + b)
print(a * b)
print(a / b)
print(a - b)
print(a ** 2)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[-5 -5 -5 -5 -5]
[ 1  4  9 16 25]


In [5]:
import numpy as np

print(np.arange(9).reshape(3, 3))

arr2 = np.arange(21)
arr2[arr2 % 2 == 0] = 0
print(arr2)
mat3 = np.random.rand(5, 5)
print(mat3.mean())
print(mat3.max(axis=1))
print(np.arange(12).reshape(3, 4))
arr5 = np.array([10, 20, 30])
print(arr5 / 5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0]
0.41826517948078973
[0.96990985 0.52475643 0.61185289 0.78517596 0.94888554]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[2. 4. 6.]


In [6]:
import numpy as np 
a = np.array([1, 2, 3, 4, 5])
print(a)
print(np.arange(10))
print(np.linspace(0,1,5))
print(np.zeros((2, 3)))
print(np.ones((3, 4)))
print(np.random.random(5))

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.96563203 0.80839735 0.30461377 0.09767211 0.68423303]


In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(np.arange(1,56))
print(np.array([1, 2, 3, 4, 5]))
print(np.zeros((2,3)))
print(np.ones((3,4)))
print(np.random.random(5))
print(np.random.randint(1, 10, size=(3, 3)))
print(np.linspace(0,1,5))
print(np.logspace(0,1,5))
print(np.eye(4))
print(np.full((2,3), 7))
print(np.random.seed(42))
print(np.repeat(np.array([1, 2]), 3))
print(np.tile(np.array([1, 2]), 3))
print(np.random.rand(3, 3))
print(np.diag(np.array([1, 2, 3])))
print(np.identity(5))
print(np.tril)

[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55]
[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.01740861 0.96975207 0.98738125 0.33841415 0.79008938]
[[1 5 3]
 [5 1 5]
 [5 8 5]]
[0.   0.25 0.5  0.75 1.  ]
[ 1.          1.77827941  3.16227766  5.62341325 10.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7 7]
 [7 7 7]]
None
[1 1 1 2 2 2]
[1 2 1 2 1 2]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<function tril at 0x0000017AE971FA60>


In [8]:
arr = np.arange(9)
print(arr.reshape(3, 3))
print(arr.reshape(-1, 1))
print(arr.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[0 1 2 3 4 5 6 7 8]


In [9]:
import numpy as np 
arr = np.array([1,2,3,4,5,6])
print(arr + 10)
print(arr * 2)

[11 12 13 14 15 16]
[ 2  4  6  8 10 12]


In [10]:
arr = np.array([10, 20, 30, 40])
print(arr[arr > 25])           # Sirf 25 se bade numbers
arr[arr < 20] = 0              # 20 se chote saare numbers ko 0 bana do
print(arr)

[30 40]
[ 0 20 30 40]


In [11]:
# indexing and slicing
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a[0])
print(a[:, 1])
print(a[0, :])

[1 2 3]
[2 5]
[1 2 3]


In [12]:
# Aggregations
import numpy as np 
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(data.mean())
print(data.std())
print(data.sum())
print(data.min())
print(data.max())

5.0
2.581988897471611
45
1
9
