In [1]:
# numpy practice 
import numpy as np 
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a + b)
print(a * b)
print(a / b)
print(a - b)
print(a ** 2)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[-5 -5 -5 -5 -5]
[ 1  4  9 16 25]


In [2]:
import numpy as np

print(np.arange(9).reshape(3, 3))

arr2 = np.arange(21)
arr2[arr2 % 2 == 0] = 0
print(arr2)

mat3 = np.random.rand(5, 5)
print(mat3.mean())
print(mat3.max(axis=1))

print(np.arange(12).reshape(3, 4))

arr5 = np.array([10, 20, 30])
print(arr5 / 5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0]
0.4955667702695265
[0.63297217 0.91682693 0.93744861 0.97317979 0.77192484]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[2. 4. 6.]
